import React from "react"
import Typography from '@mui/material/Typography';
import Paper from '@mui/material/Paper';
import { GetPaddedStyle } from './theme.js'

function Legal() {

    const style = GetPaddedStyle()
    style.maxWidth = 1000
    
    return <Paper elevation={3} sx={style}>
    <Typography variant="h2">
    EULA
    </Typography>
    <Typography variant="body2" display="block" sx={{ textAlign: 'justify', textJustify: 'inter-word'}}>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed eros in ex suscipit lacinia nec sed sem. Pellentesque non efficitur diam. Sed massa purus, fermentum vel egestas sit amet, ultrices nec libero. Cras bibendum posuere consequat. Donec non pretium ipsum. Proin arcu libero, tempor fringilla aliquet ac, egestas eu dolor. Sed porta in nisi quis rhoncus. Etiam bibendum finibus felis, at efficitur tellus ornare vitae. Mauris vestibulum eget purus in rhoncus. Vivamus consectetur mi felis, in mollis sem luctus eu.

Pellentesque mattis felis sapien, ut lacinia lorem gravida nec. Suspendisse mauris ligula, egestas et ipsum in, varius dignissim magna. Aliquam finibus ligula ut imperdiet elementum. In vitae lacus vestibulum, viverra lorem ac, dictum diam. Vestibulum sed ultrices ante, aliquet fermentum ex. Maecenas lacinia sapien tellus, vel malesuada sapien iaculis a. Aliquam congue venenatis iaculis. Fusce sed ullamcorper orci.

Nunc id fermentum nisl, eu tempus sem. Nam luctus consectetur fringilla. Morbi fermentum lobortis erat, at mattis orci fringilla non. Duis ac consectetur orci, sed congue nibh. Nam facilisis dapibus quam volutpat porta. Sed nec massa pharetra orci commodo ultricies. Suspendisse gravida auctor diam a maximus. Vestibulum at sapien viverra, dignissim sapien in, rutrum ante.

Mauris quam sem, tempor et facilisis feugiat, tristique vel nisi. Curabitur sollicitudin mi vel posuere accumsan. Curabitur ante metus, faucibus non est nec, fringilla ornare neque. Integer condimentum diam eget leo suscipit venenatis. Vestibulum vitae sem lobortis est tempus sagittis posuere et mauris. Etiam iaculis nisl id mollis pharetra. Nunc in posuere velit, et dignissim nunc. Curabitur lobortis auctor lacus non lobortis. Donec vulputate, ipsum ut euismod auctor, massa magna tincidunt dolor, ac imperdiet justo tortor vitae arcu. Quisque viverra velit id convallis varius. Maecenas pulvinar elit nibh, sit amet ultrices magna fringilla vitae. Nam vel tempor tellus. Integer mauris libero, mollis porttitor mauris maximus, maximus pretium quam. Nulla elementum lacus non mollis feugiat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Donec suscipit imperdiet mollis. Pellentesque ac quam dignissim, eleifend velit eget, elementum metus. Suspendisse pulvinar facilisis nibh, a luctus nibh feugiat a. Aliquam varius egestas aliquam. Nulla sed arcu enim. Ut luctus a nunc quis dignissim. In sollicitudin, risus eget varius auctor, mauris velit blandit nisi, at condimentum nunc nisi sit amet augue. Ut consequat arcu lacinia, convallis est sit amet, facilisis diam. Curabitur vitae bibendum ligula. Aenean dapibus rutrum sapien, vitae laoreet libero dapibus vel.
</Typography>
<Typography variant="h4" component="h3">1. Lorem</Typography>
<Typography variant="body2" display="block" sx={{ textAlign: 'justify', textJustify: 'inter-word'}}>
Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer lobortis, purus quis porttitor euismod, velit nulla aliquet mi, a fermentum est lorem vel ante. Quisque iaculis, nunc id ullamcorper sagittis, eros nisl dictum sem, nec iaculis metus ante at ante. Fusce elit quam, tristique eu nibh vitae, euismod hendrerit enim. Duis aliquet est ex, nec convallis velit maximus at. Ut vitae dui tincidunt, cursus mi ac, feugiat tellus. Nunc dignissim ipsum nec sem tincidunt, nec mollis nisl consequat. Praesent ac maximus lorem, a eleifend est. Nunc pretium, nisi id feugiat imperdiet, ipsum libero volutpat leo, eget consectetur ipsum enim et sem. Morbi finibus gravida nisi, at egestas sapien sodales ac. Aenean hendrerit nunc eu turpis condimentum tincidunt. Duis ac purus in massa hendrerit facilisis. Aliquam pellentesque facilisis purus, ac malesuada ex euismod sit amet. Vestibulum sed efficitur lacus. Ut eget blandit augue. Nulla massa dolor, consectetur sed mi non, aliquet posuere erat.

In ullamcorper tempor justo id vehicula. Etiam ante lacus, consectetur vel eros eget, ultrices tempus eros. Fusce sollicitudin sit amet augue ac viverra. Quisque tincidunt lobortis eleifend. Morbi vehicula volutpat tellus, ac pharetra erat. Nunc non orci vel tellus tristique tempus at sit amet est. Mauris tempus fermentum metus.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed erat odio, efficitur quis magna a, luctus porta massa. Donec semper lorem sagittis lorem condimentum, id molestie lacus lacinia. Aliquam suscipit at purus sit amet vestibulum. Cras interdum nisi ac placerat lacinia. Nam nec finibus elit, ac interdum ligula. Cras lobortis viverra tellus, eu congue massa interdum quis. Duis lacinia augue vel elit tempor, porta tristique eros iaculis. Quisque urna justo, rhoncus at tortor non, accumsan condimentum leo.

Donec id neque ullamcorper, malesuada purus sit amet, porttitor lacus. Nam id vestibulum erat. Suspendisse potenti. Mauris aliquam et augue sit amet elementum. Nunc suscipit ex eu risus ultricies, eget hendrerit elit pulvinar. Nulla pretium aliquet quam, at facilisis diam egestas at. Integer urna quam, pellentesque sed dui quis, mollis venenatis nisl. Praesent aliquet elit nec sagittis vulputate. Pellentesque condimentum, ante sed maximus pretium, odio turpis ultricies massa, eu posuere nulla diam vitae turpis. Curabitur elementum eu lorem sit amet ornare. Fusce ut turpis arcu. In semper dapibus scelerisque. Nulla dolor arcu, pellentesque congue augue a, cursus luctus odio. Donec sagittis neque sed odio sodales, at ultricies nunc vehicula.

Phasellus nibh velit, elementum sit amet purus id, mattis congue lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis vitae nibh nec ante sagittis aliquet et sit amet nisi. Etiam interdum malesuada mauris, in tristique justo ullamcorper eu. Proin ultrices, orci vitae aliquet dignissim, magna urna rutrum nisi, a vehicula magna nibh vel leo. Maecenas eget egestas ligula. Integer auctor arcu non arcu feugiat, vitae sodales tellus imperdiet. Donec nec elit turpis. Donec non eros eu mauris pulvinar aliquam non vel mi. Nulla facilisi. Pellentesque bibendum lorem erat, nec volutpat dui efficitur id. Fusce semper felis quis aliquam aliquet.

Integer gravida iaculis odio. Ut rutrum neque a justo blandit pulvinar. Maecenas in tellus dictum, faucibus enim a, porttitor mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non libero leo. Nam sed ligula elit. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec quis feugiat lorem. Suspendisse nec justo ac ligula aliquet tincidunt. Sed interdum urna vitae ultricies ornare. Praesent id velit sit amet felis consectetur placerat a nec tortor. Fusce finibus mauris at semper sagittis. In ultricies rutrum libero, vitae suscipit felis scelerisque condimentum. Sed vitae lacinia metus. Nunc nec porta ligula.

Nulla eget sem porttitor, egestas libero vitae, scelerisque nulla. Ut iaculis elit et pulvinar porta. Aliquam erat volutpat. Mauris euismod sagittis mauris. Sed a enim porta, lacinia odio sed, tincidunt risus. Donec sodales enim et neque pretium pretium. Nam neque ligula, sollicitudin quis porttitor ac, viverra et felis. Morbi commodo magna mauris, eget pretium massa fringilla eu.

Nullam cursus arcu et enim laoreet, id finibus elit venenatis. Curabitur sit amet vehicula metus. Proin in pulvinar lacus, nec consectetur leo. Nam in bibendum ante, vel tristique nisi. Integer gravida erat at elementum aliquam. Cras hendrerit nec magna a sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris eu massa nunc. Nam eu euismod ligula. Vestibulum ut euismod est. Nam nisi purus, lacinia ac mi vitae, maximus sollicitudin lacus.

Nullam nisi dolor, finibus vitae neque facilisis, consectetur facilisis est. In in urna ut tellus porta placerat eget at ipsum. Nullam elementum leo non vehicula imperdiet. Suspendisse posuere dui vitae mauris vulputate, et imperdiet orci euismod. Vestibulum congue leo in fringilla congue. Suspendisse laoreet posuere consequat. Maecenas nec laoreet nisl. Phasellus malesuada, dui a laoreet ultricies, felis ante sagittis dui, ut tempus nunc justo eu orci. Nulla facilisi. Suspendisse diam lectus, interdum non dapibus vel, varius sed felis. Proin consequat imperdiet turpis, eu dapibus orci molestie a.
</Typography>
<Typography variant="h4" component="h3">2. Ipsum</Typography>
<Typography variant="body2" display="block" sx={{ textAlign: 'justify', textJustify: 'inter-word'}}>
Suspendisse fermentum lorem sed feugiat lacinia. Aenean efficitur, risus interdum viverra aliquet, ligula quam molestie libero, vitae tincidunt mauris lacus at tortor. Nam faucibus ante et convallis gravida. Nulla nibh magna, bibendum at mi maximus, dignissim ultrices metus. Nulla libero turpis, malesuada in dignissim eu, tempus sit amet mi. Donec sit amet hendrerit metus. Aenean tristique odio convallis turpis ultricies aliquet. Donec porttitor elit facilisis nunc mattis aliquet.

Donec pellentesque rutrum nunc, vel bibendum leo condimentum nec. Ut sed ullamcorper sapien, ut accumsan est. Morbi tempus dolor consectetur ex iaculis blandit. In vestibulum pellentesque scelerisque. Curabitur dictum lorem non lacus tincidunt porta. Nam eleifend sapien id aliquet semper. In hac habitasse platea dictumst. Duis libero neque, euismod vitae facilisis at, tristique in nisl. Vestibulum tincidunt, mauris nec ultricies condimentum, tortor neque rutrum leo, ut posuere sem dolor ac purus. Nullam eget dictum tellus. Cras tempor nibh a velit condimentum, a condimentum nisi efficitur. Duis nulla lacus, posuere in nibh imperdiet, sagittis lobortis dui. Phasellus tincidunt gravida nunc, at egestas sem aliquet et. Praesent ultrices elit magna, nec mollis ipsum convallis quis.

In tempus, massa non mattis semper, enim ligula tincidunt est, eget rutrum dui erat vel mauris. Vivamus sed aliquam velit. Quisque a odio justo. Cras fringilla non odio eget auctor. Praesent condimentum sem quis risus molestie luctus. Praesent posuere velit nisl, in maximus quam dictum ac. Praesent a ex varius ex dapibus vestibulum et id enim. Nulla dignissim tincidunt varius. Suspendisse condimentum eros nunc.

Vivamus et tristique sem, eu ultrices ante. Maecenas quis dolor faucibus, ultrices ligula nec, molestie velit. Aenean vitae urna feugiat, aliquam justo at, auctor odio. Aliquam non ornare ipsum. Cras vel odio facilisis, mollis libero id, porta risus. Proin vel metus ut nisl iaculis sagittis convallis id risus. Morbi imperdiet ullamcorper magna non pharetra. Nulla suscipit mauris leo, nec semper nunc pellentesque at.

Curabitur pharetra lacus sed est lobortis imperdiet. Donec sagittis, justo id vulputate vehicula, metus sapien ullamcorper ante, et euismod turpis erat ut sem. Sed dui justo, hendrerit non ipsum quis, lobortis tristique purus. Sed et lobortis nibh, nec semper felis. Amogus. Sed semper pulvinar dolor sed volutpat. Aliquam erat volutpat. Ut a eros sed erat suscipit sodales eu et libero. Fusce dapibus maximus sem, vitae ullamcorper nunc. Nullam porta pulvinar neque sed interdum. Suspendisse vehicula ullamcorper tortor, dictum semper lacus rhoncus quis. Ut quis felis augue. Cras nunc leo, fringilla id porta a, lacinia a quam. Maecenas pretium diam nec elit varius posuere id quis ligula. Fusce pellentesque ipsum ac purus auctor, vel sollicitudin neque ornare. Morbi lacinia ac sem vitae pellentesque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Proin sodales nisl vel justo tincidunt dignissim. Nullam dapibus vestibulum elit vel efficitur. Nunc id erat ex. Curabitur iaculis, urna eget dapibus placerat, eros libero tincidunt ligula, fermentum efficitur sem massa in ante. Morbi vel efficitur ante. Nulla sodales augue eget dui egestas, vel consequat ante efficitur. Suspendisse sed felis tortor. Morbi a aliquam tellus. Sed feugiat arcu ut sapien pellentesque, ut imperdiet mauris mollis. Curabitur nisl sapien, ornare lobortis libero non, finibus venenatis eros. Ut porta maximus quam in interdum. Maecenas at sapien posuere, vestibulum magna ac, elementum risus. Sed non tellus eget magna elementum efficitur. Sed sit amet aliquet turpis.

Donec at nunc fringilla, rhoncus nisi eget, iaculis lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et arcu nec ligula fringilla tempor vel a sapien. Nullam in tellus vitae libero volutpat mollis a nec magna. Fusce dolor diam, rhoncus ac magna non, lacinia tristique purus. Nullam et urna faucibus, vulputate libero nec, consequat turpis. Nullam ac feugiat urna. Quisque commodo odio eget egestas suscipit. Quisque dictum hendrerit diam, in tristique risus fringilla vel. Ut posuere libero nisi, quis tempus elit vestibulum vel. Donec commodo eros in massa sodales mollis. Nulla in auctor nisi.
</Typography>
<Typography variant="h4" component="h3">3. Dolor</Typography>
<Typography variant="body2" display="block" sx={{ textAlign: 'justify', textJustify: 'inter-word'}}>
Nam sollicitudin nulla ligula, nec faucibus augue vulputate vel. Nunc luctus arcu lectus, non rhoncus augue faucibus tincidunt. Sed mollis sollicitudin libero, at dapibus odio viverra vel. Duis leo dui, maximus eu urna in, malesuada ornare lorem. Integer semper in metus at pharetra. Vestibulum vitae sem libero. In libero libero, finibus a consectetur non, consequat ut nunc. Nullam non auctor tellus.

Nunc imperdiet nisl in lacus consequat, vel elementum orci varius. Integer luctus mauris id quam ultricies accumsan. Fusce mi velit, aliquam scelerisque ipsum placerat, egestas commodo massa. Aliquam id aliquam orci. Ut augue urna, tempor eu nisl vitae, egestas ultricies libero. Donec lectus erat, dignissim vitae felis elementum, tincidunt finibus purus. Donec in pharetra eros. Mauris et rutrum magna. Praesent faucibus velit ut dictum auctor. Curabitur euismod lorem et fringilla iaculis. Aenean vel ante non leo porttitor fringilla a ut ante.

Nunc vulputate risus eu orci faucibus, sit amet lobortis nisl venenatis. Proin a imperdiet orci. Donec a tortor nec nisi tincidunt interdum. Proin blandit tincidunt erat nec malesuada. Fusce volutpat eget nisi ac pulvinar. Sed accumsan bibendum tempus. In est nibh, sagittis fringilla volutpat sed, volutpat in velit. Sed posuere cursus ipsum, a scelerisque est porttitor sed. Cras pellentesque, diam quis luctus lacinia, turpis nunc tincidunt massa, ut dictum mi massa id leo. Nullam tristique diam quis urna scelerisque auctor.

Sed molestie fermentum vestibulum. Morbi eleifend pretium turpis quis porta. Etiam congue dolor quis augue sollicitudin porttitor. Aliquam condimentum, elit sed ornare interdum, erat dolor ornare neque, scelerisque luctus velit magna vel enim. Phasellus tincidunt, elit at euismod tristique, turpis felis dictum magna, a vulputate lectus elit vel sapien. In nisl purus, pharetra vel faucibus eget, viverra a sapien. Fusce imperdiet luctus enim, vitae imperdiet turpis feugiat tincidunt. Proin eget diam pretium eros pulvinar lobortis. Ut accumsan augue non dui rhoncus porta.

Ut rhoncus, arcu eu rhoncus posuere, ante dui finibus diam, a pulvinar libero tellus eget nulla. Donec sit amet erat accumsan, aliquam tellus non, posuere eros. Phasellus non lobortis augue, sit amet blandit neque. Phasellus non euismod lacus. Donec porttitor sem et arcu semper imperdiet. Duis ornare ante at eros sodales imperdiet. Nullam mattis augue est, molestie eleifend nibh sollicitudin non. Aenean vitae nunc placerat, tempor neque nec, ullamcorper odio. Integer posuere ultrices magna, id viverra lectus pretium a. Sed at nunc hendrerit, bibendum sem interdum, vehicula mi. Donec placerat massa eu massa maximus iaculis. Praesent accumsan luctus massa non sagittis.

Praesent lacus tortor, aliquet non erat at, euismod aliquam ante. Phasellus imperdiet nulla ultrices libero venenatis pulvinar. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ornare a lorem id congue. Nunc eget enim ac lorem mollis rutrum vel ut sem. Nulla viverra iaculis nunc, ac molestie tortor. Maecenas at libero id lectus malesuada tempus. Suspendisse lectus leo, semper id volutpat at, vehicula in nunc.

Proin ac malesuada nisl, id congue metus. Aenean id bibendum turpis. Sed elit est, volutpat nec felis in, rutrum ultricies massa. Aliquam ex justo, maximus vel sem nec, scelerisque eleifend ante. Pellentesque ut urna quis justo lacinia mollis sed vitae nulla. Aliquam diam massa, facilisis quis imperdiet in, pharetra vitae tortor. Aenean viverra ex ac nulla dignissim pharetra. Nulla aliquam pharetra enim vel sodales. Curabitur vitae ultricies metus. In tincidunt sagittis eros. Vivamus lobortis velit nibh, nec auctor mauris facilisis ac. Vestibulum cursus diam id urna hendrerit, nec finibus augue commodo. Aliquam porttitor, nisi ut commodo finibus, risus sem pharetra tellus, dapibus egestas nulla mauris ut ante. Maecenas mollis semper sem in faucibus. Proin sed vehicula sapien.

Suspendisse ultrices dui justo, eu vehicula dolor malesuada in. Sed sit amet suscipit dui, a hendrerit nisi. Donec at orci eget felis imperdiet gravida id vel nunc. Duis a pulvinar mauris. Morbi at arcu nulla. Aliquam purus felis, imperdiet vel scelerisque ut, porttitor quis odio. Aenean id consectetur leo. Vivamus faucibus urna vitae euismod accumsan. Pellentesque sed bibendum erat, in feugiat nisi. Aenean sollicitudin placerat justo, a consectetur risus finibus faucibus. Duis lacus dolor, commodo nec erat sit amet, maximus molestie eros. Nunc et ex a felis finibus sagittis eu ut ante. Mauris non mi eu ante mattis cursus ut placerat lectus. Integer egestas interdum pulvinar. Phasellus bibendum volutpat tempor. Duis in consequat metus.

Nullam consequat felis quis risus viverra finibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam in accumsan ante. Maecenas tincidunt scelerisque neque ac condimentum. Vestibulum porta dolor diam, vel maximus purus ullamcorper eu. Vestibulum gravida ligula velit, at egestas purus consequat sit amet. Nam sodales tempor leo id accumsan. Phasellus sed tellus a nunc feugiat blandit. Sed eu justo elementum, facilisis libero eu, blandit justo. Praesent gravida turpis quis tincidunt egestas.
</Typography>
</Paper>
}

export default Legal